# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_data.proto\x12\nSensorData\"3\n\x0fSensorDataEntry\x12\x11\n\ttime_span\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\";\n\x0eSensorDataList\x12)\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1b.SensorData.SensorDataEntryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORDATAENTRY._serialized_start=33
  _SENSORDATAENTRY._serialized_end=84
  _SENSORDATALIST._serialized_start=86
  _SENSORDATALIST._serialized_end=145
# @@protoc_insertion_point(module_scope)
